export default {
  CacheSize: 4096,
  ReaderReadAHead: 95,
  PreloadCache: 150,
  UseDisk: true,
  TorrentsSavePath: '/opt/ts',
  RemoveCacheOnDrop: false,
  ForceEncrypt: false,
  RetrackersMode: 1,
  TorrentDisconnectTimeout: 30,
  EnableDebug: false,
  EnableDLNA: false,
  FriendlyName: '',
  EnableRutorSearch: false,
  EnableIPv6: false,
  DisableTCP: false,
  DisableUTP: false,
  DisableUPNP: false,
  DisableDHT: false,
  DisablePEX: false,
  DisableUpload: false,
  DownloadRateLimit: 0,
  UploadRateLimit: 0,
  ConnectionsLimit: 25,
  PeersListenPort: 0,
  ResponsiveMode: true,
  SslPort: 0,
  SslCert: '',
  SslKey: '',
  ShowFSActiveTorr: true,
  StoreSettingsInJson: true,
  EnableProxy: false,
  ProxyHosts: ['*themoviedb.org', '*tmdb.org', 'rutor.info'],
  AutoDownload: false,
  PreloadSizeMB: 50,
}
